### ISSUE TITLE
Criação da tela Home

### ISSUE THREAD

**Issue by almadaj** [marcelinombb/NutriMate#4]
Criação do Header que contará com um Container de boas-vindas com o nome do usuário, um ícone da sessão de notificação e ao lado a foto que será direcionado para a área de Profile

**Comment by marcelinombb** [comment]
Tela Home criada ficaram faltando somente os icones dos desafios e os botões de notificação e perfil.

utilizei esse video como referência para criação dos cards https://www.youtube.com/watch?v=9LqUkiNleqU&list=LL&index=13

**Comment by marcelinombb** [comment]
e também não consegui achar como baixar as imagens de background dos cards então essas que utilizei estão com pouca qualidade.
